// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynlxlmthtvqunayfnttz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlubHhsbXRodHZxdW5heWZudHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTIzNTIsImV4cCI6MjA3MTI4ODM1Mn0.r07RRXgkSaXrKVNwb_5c_-mLSlyLmgec1cZgk6Z2Tg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});